cryptokilla/cryptokilla/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('market/', include('market.urls')),
    path('', include('landing.urls')),
    path('trading/', include('trading.urls')),
    path('', include('stats.urls')),
]

cryptokilla/market/urls.py
from django.urls import path
from .views import (
    CryptocurrencyListView, CryptocurrencyDetailView,
    CryptocurrencyCreateView, CryptocurrencyUpdateView, CryptocurrencyDeleteView,
    TradingPairListView, TradingPairDetailView, TradingPairCreateView, TradingPairUpdateView, TradingPairDeleteView,
    CryptocurrencyNewsDetailView,
    CryptocurrencyNewsListView, CryptocurrencyNewsCreateView, CryptocurrencyNewsUpdateView, CryptocurrencyNewsDeleteView
)


urlpatterns = [
    # Cryptocurrency URLs
    path('cryptocurrencies/', CryptocurrencyListView.as_view(), name='cryptocurrency-list'),
    path('cryptocurrencies/<int:pk>/', CryptocurrencyDetailView.as_view(), name='cryptocurrency-detail'),
    path('cryptocurrencies/create/', CryptocurrencyCreateView.as_view(), name='cryptocurrency-create'),
    path('cryptocurrencies/<int:pk>/update/', CryptocurrencyUpdateView.as_view(), name='cryptocurrency-update'),
    path('cryptocurrencies/<int:pk>/delete/', CryptocurrencyDeleteView.as_view(), name='cryptocurrency-delete'),

    # TradingPair URLs
    path('tradingpairs/', TradingPairListView.as_view(), name='tradingpair-list'),
    path('tradingpairs/<int:pk>/', TradingPairDetailView.as_view(), name='tradingpair-detail'),
    path('tradingpairs/create/', TradingPairCreateView.as_view(), name='tradingpair-create'),
    path('tradingpairs/<int:pk>/update/', TradingPairUpdateView.as_view(), name='tradingpair-update'),
    path('tradingpairs/<int:pk>/delete/', TradingPairDeleteView.as_view(), name='tradingpair-delete'),

    # CryptocurrencyNews URLs
    path('cryptocurrencynews/', CryptocurrencyNewsListView.as_view(), name='cryptocurrencynews-list'),
    path('cryptocurrencynews/<int:pk>/', CryptocurrencyNewsDetailView.as_view(), name='cryptocurrencynews-detail'),
    path('cryptocurrencynews/create/', CryptocurrencyNewsCreateView.as_view(), name='cryptocurrencynews-create'),
    path('cryptocurrencynews/<int:pk>/update/', CryptocurrencyNewsUpdateView.as_view(), name='cryptocurrencynews-update'),
    path('cryptocurrencynews/<int:pk>/delete/', CryptocurrencyNewsDeleteView.as_view(), name='cryptocurrencynews-delete'),
]

cryptokilla/stats/urls.py
# statistics/urls.py
from django.urls import path
from .views import UserVisitListView

urlpatterns = [
    path('stats/', UserVisitListView.as_view(), name='stats'),
    # Add more URLs as needed
]

cryptokilla/market/models.py
from django.db import models
from django.utils import timezone

# Create your models here.
class Cryptocurrency(models.Model):
    name = models.CharField(max_length=50)
    symbol = models.CharField(max_length=10)
    description = models.TextField(blank=True, null=True)
    website = models.URLField(blank=True, null=True)
    icon = models.ImageField(upload_to='cryptocurrency_icons/', blank=True, null=True)
    is_stablecoin = models.BooleanField(default=False)  # Add this field
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"{self.name} ({self.symbol})"


class TradingPair(models.Model):
    base_currency = models.ForeignKey(Cryptocurrency, related_name='base_currency', on_delete=models.CASCADE)
    quote_currency = models.ForeignKey(Cryptocurrency, related_name='quote_currency', on_delete=models.CASCADE)

    def __str__(self):
        return f"{self.base_currency.symbol}/{self.quote_currency.symbol}"

class CryptocurrencyNews(models.Model):
    cryptocurrency = models.ForeignKey(Cryptocurrency, on_delete=models.CASCADE)
    title = models.CharField(max_length=255)
    content = models.TextField()
    source = models.URLField()
    timestamp = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return f"{self.cryptocurrency.name} News: {self.title}"

cryptokilla/trading/models.py
# trading/models.py
from django.db import models
from users.models import CustomUser
from market.models import TradingPair

class TradeActionEnum(models.TextChoices):
    BUY = 'buy', 'Buy'
    SELL = 'sell', 'Sell'

class TradeStatusEnum(models.TextChoices):
    OPEN = 'open', 'Open'
    CLOSED = 'closed', 'Closed'

class NotificationTypeEnum(models.TextChoices):
    EMAIL = 'email', 'Email'
    SMS = 'sms', 'Sms'




class Strategy(models.Model):
    name = models.CharField(max_length=50)
    description = models.TextField()

    def execute_strategy(self, trading_bot, opportunity):
        raise NotImplementedError("Subclasses must implement this method")

class TrendFollowingStrategy(Strategy):
    # You can add specific fields for the Trend Following strategy here
    pass

class TradingBot(models.Model):
    user = models.ForeignKey(CustomUser, on_delete=models.CASCADE)
    bot_name = models.CharField(max_length=255)
    allocated_capital = models.FloatField()
    current_capital = models.FloatField()
    risk_percentage = models.FloatField()  # Percentage of capital to risk per trade
    strategy = models.ForeignKey(Strategy, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)

class Trade(models.Model):
    user = models.ForeignKey(CustomUser, on_delete=models.CASCADE)
    trading_bot = models.ForeignKey(TradingBot, on_delete=models.CASCADE)
    trading_pair = models.ForeignKey(TradingPair, on_delete=models.CASCADE)
    action = models.CharField(max_length=4, choices=TradeActionEnum.choices)
    quantity = models.FloatField()
    price = models.FloatField()
    timestamp = models.DateTimeField(auto_now_add=True)
    status = models.CharField(max_length=10, choices=TradeStatusEnum.choices)

class Notification(models.Model):
    user = models.ForeignKey(CustomUser, on_delete=models.CASCADE)
    notification_type = models.CharField(max_length=10, choices=TradeStatusEnum.choices)
    content = models.TextField()
    timestamp = models.DateTimeField(auto_now_add=True)

class Opportunity(models.Model):
    trading_pair = models.CharField(max_length=10)
    time_frame = models.CharField(max_length=10)
    strategy_type = models.CharField(max_length=50)
    status = models.CharField(max_length=10)  # open or closed
    details = models.TextField()
    timestamp = models.DateTimeField(auto_now_add=True)

class Backtest(models.Model):
    user = models.ForeignKey(CustomUser, on_delete=models.CASCADE)
    trading_pair = models.CharField(max_length=10)
    strategy_parameters = models.TextField()
    performance_metrics = models.TextField()
    timestamp = models.DateTimeField(auto_now_add=True)

class Log(models.Model):
    user = models.ForeignKey(CustomUser, on_delete=models.CASCADE)
    log_message = models.TextField()
    timestamp = models.DateTimeField(auto_now_add=True)

cryptokilla/market/views.py
from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView
from .models import Cryptocurrency, TradingPair, CryptocurrencyNews
from channels.layers import get_channel_layer
from asgiref.testing import ApplicationCommunicator



class CryptocurrencyListView(ListView):
    model = Cryptocurrency
    template_name = 'market/cryptocurrency_list.html'  # Create a template for displaying the list
    context_object_name = 'cryptocurrencies'
    paginate_by = 10  # Adjust the number of cryptocurrencies per page if needed

class CryptocurrencyDetailView(DetailView):
    model = Cryptocurrency
    template_name = 'market/cryptocurrency_detail.html'  # Create a template for displaying the details

class TradingPairListView(ListView):
    model = TradingPair
    template_name = 'market/trading_pair_list.html'  # Create a template for displaying the list
    context_object_name = 'trading_pairs'
    paginate_by = 10  # Adjust the number of trading pairs per page if needed

class CryptocurrencyNewsListView(ListView):
    model = CryptocurrencyNews
    template_name = 'market/cryptocurrency_news_list.html'  # Create a template for displaying the list
    context_object_name = 'cryptocurrency_news'
    paginate_by = 10  # Adjust the number of news articles per page if needed
    ordering = ['-timestamp']  # Show the latest news first

class CryptocurrencyNewsDetailView(DetailView):
    model = CryptocurrencyNews
    template_name = 'market/cryptocurrency_news_detail.html'  # Create a template for displaying the details


class CryptocurrencyCreateView(CreateView):
    model = Cryptocurrency
    template_name = 'market/cryptocurrency_form.html'  # Create a template for the form
    success_url = reverse_lazy('cryptocurrency-list') 
    fields = ['name', 'symbol', 'description', 'website', 'icon', 'is_stablecoin']

class CryptocurrencyUpdateView(UpdateView):
    model = Cryptocurrency
    template_name = 'market/cryptocurrency_form.html'  # Create a template for the form
    fields = ['name', 'symbol', 'description', 'website', 'icon', 'is_stablecoin']

class CryptocurrencyDeleteView(DeleteView):
    model = Cryptocurrency
    template_name = 'market/cryptocurrency_confirm_delete.html'  # Create a template for confirmation
    success_url = reverse_lazy('cryptocurrency-list')  # Redirect to the cryptocurrency list view after deletion

# Repeat similar views for TradingPair and CryptocurrencyNews
class TradingPairDetailView(DetailView):
    model = TradingPair
    template_name = 'market/trading_detail.html'  # Create a template for displaying the details

class TradingPairCreateView(CreateView):
    model = TradingPair
    template_name = 'market/trading_pair_form.html'  # Create a template for the form
    fields = ['base_currency', 'quote_currency']

class TradingPairUpdateView(UpdateView):
    model = TradingPair
    template_name = 'market/trading_pair_form.html'  # Create a template for the form
    fields = ['base_currency', 'quote_currency']

class TradingPairDeleteView(DeleteView):
    model = TradingPair
    template_name = 'market/trading_pair_confirm_delete.html'  # Create a template for confirmation
    success_url = reverse_lazy('tradingpair-list')  # Redirect to the trading pair list view after deletion

class CryptocurrencyNewsDetailView(DetailView):
    model = CryptocurrencyNews
    template_name = 'market/cryptocurrency_news_detail.html'  # Create a template for displaying the details

class CryptocurrencyNewsCreateView(CreateView):
    model = CryptocurrencyNews
    template_name = 'market/cryptocurrency_news_form.html'  # Create a template for the form
    fields = ['cryptocurrency', 'title', 'content', 'source']
    success_url = reverse_lazy('cryptocurrencynews-list')
    
class CryptocurrencyNewsUpdateView(UpdateView):
    model = CryptocurrencyNews
    template_name = 'market/cryptocurrency_news_form.html'  # Create a template for the form
    fields = ['cryptocurrency', 'title', 'content', 'source']

class CryptocurrencyNewsDeleteView(DeleteView):
    model = CryptocurrencyNews
    template_name = 'market/cryptocurrency_news_confirm_delete.html'  # Create a template for confirmation
    success_url = reverse_lazy('cryptocurrencynews-list')  # Redirect to the news list view after deletion

async def trigger_news_update(news_message):
    channel_layer = get_channel_layer()
    await channel_layer.group_send('news_group', {'type': 'send.news.update', 'message': news_message})

def add_cryptocurrency_news(request):
    # Your logic to add a new CryptocurrencyNews instance
    new_news = CryptocurrencyNews.objects.create(
        cryptocurrency=some_cryptocurrency_instance,
        title="New News Title",
        content="News content goes here.",
        source="https://example.com",
    )

    # Trigger WebSocket event to broadcast news update
    trigger_news_update(new_news.title)
    return HttpResponse("News added successfully")

cryptokilla/market/templates/market/cryptocurrency_confirm_delete.html
{% extends 'landing/base.html' %}

{% block content %}
  <h2>Confirm Deletion</h2>
  <p>Are you sure you want to delete "{{ tradingpair}}"?</p>
  <form method="post">
    {% csrf_token %}
    <button type="submit" class="btn btn-danger">Confirm</button>
  </form>
  <a href="{% url 'tradingpair-list' %}" class="btn btn-secondary">Cancel</a>
{% endblock %}

cryptokilla/market/templates/market/cryptocurrency_detail.html
{% extends 'landing/base.html' %}
{%load static%}
{% load crispy_forms_tags %}

{% block extra_css %}

<style>
    :root {
        --main-font: 'Poppins', sans-serif;
        /*TO DO : to be selected from a list */
        --default-text-color: rgb(255, 255, 255);
        /* Can be selected by user */
        --background-image-url: url('{% static 'landing/images/header-background.jpg' %}');
        /* sizes: 1280x720 or 1920x1080 */
        --background-color-default: rgb(0, 0, 0, 0.3);
        --navbar-background-color: transparent;
        --navbar-scrolled-background-color: rgba(0, 0, 0, 0.3);
        --navbar-scrolled-background-blur: 10px;
        /*--btn-navbar-background-color: {{config.navbar_btn_color}};*/
    }

    body {
        font-family: var(--main-font);
        color: var(--default-text-color);
        background: var(--background-image-url) var(--background-color-default);
        background-blend-mode: multiply;
        background-position: center;
        background-size: cover;
        background-repeat: no-repeat;
    }

    .navbar {
        background-color: var(--navbar-background-color) !important;
        transition: all 0.5s ease-in-out;
    }

    .navbar-scrolled {
        background-color: var(--navbar-scrolled-background-color);
        backdrop-filter: blur(var(--navbar-scrolled-background-blur));
    }

    .navbar-btn {
        background-color: var(--btn-navbar-background-color);
    }
</style>
{% endblock %}

{% block content %}
  <section id="cryptocurrency-detail" class="w-80 vh-100 d-flex flex-row justify-content-center align-items-start" style="margin-top:100px;">
    <div class="container mt-5 ">
    <h2>{{ cryptocurrency.name }} ({{ cryptocurrency.symbol }}) - Detail</h2>

    <!-- Tabs Navigation -->
    <ul class="nav nav-tabs" id="cryptoTabs" role="tablist">
      <li class="nav-item">
        <a class="nav-link active" id="dashboard-tab" data-toggle="tab" href="#dashboard" role="tab" aria-controls="dashboard" aria-selected="true">Dashboard</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" id="general-tab" data-toggle="tab" href="#general" role="tab" aria-controls="general" aria-selected="false">General Info</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" id="market-tab" data-toggle="tab" href="#market" role="tab" aria-controls="market" aria-selected="false">Market Data</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" id="news-tab" data-toggle="tab" href="#news" role="tab" aria-controls="news" aria-selected="false">News</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" id="trades-tab" data-toggle="tab" href="#trades" role="tab" aria-controls="trades" aria-selected="false">Trades</a>
      </li>
    </ul>

    <!-- Tabs Content -->
    <div class="tab-content mt-3" id="cryptoTabsContent">
      <div class="tab-pane fade show active" id="dashboard" role="tabpanel" aria-labelledby="dashboard-tab">
        <h3>Your Cryptocurrency Dashboard</h3>
        <div class="row">
          <!-- Last Market Data -->
          <div class="col-6">
            <h4>Last Market Data</h4>
            {% if trading_pair.market_data %}
              <p>OHLCV Data: {{ trading_pair.market_data }}</p>
            {% else %}
              <p>No market data available.</p>
            {% endif %}
          </div>
    
          <!-- Last Trades -->
          <div class="col-6">
            <h4>Last Trades</h4>
            {% for trade in cryptocurrency.trade_set.all %}
              <div>
                <p>Action: {{ trade.get_action_display }}</p>
                <p>Quantity: {{ trade.quantity }}</p>
                <p>Price: {{ trade.price }}</p>
                <p>Timestamp: {{ trade.timestamp }}</p>
              </div>
            {% endfor %}
          </div>
        </div>
    
        <!-- Last News Releases -->
        <div class="row">
          <div class="col-12">
            <h4>Last News Releases</h4>
            {% for news in cryptocurrency.news_set.all %}
              <div>
                <p>Title: {{ news.title }}</p>
                <p>Content: {{ news.content }}</p>
                <p>Source: <a href="{{ news.source }}" target="_blank">{{ news.source }}</a></p>
                <p>Timestamp: {{ news.timestamp }}</p>
              </div>
            {% endfor %}
          </div>
        </div>
      </div>
    




      <!-- General Info Tab -->
      <div class="tab-pane fade " id="general" role="tabpanel" aria-labelledby="general-tab">
        <h3>General Information</h3>
        <p>Description: {{ cryptocurrency.description }}</p>
        <p>Website: <a href="{{ cryptocurrency.website }}" target="_blank">{{ cryptocurrency.website }}</a></p>
        <!-- Add more general information fields as needed -->
      </div>

      <!-- Market Data Tab -->
      <div class="tab-pane fade" id="market" role="tabpanel" aria-labelledby="market-tab">
        <h3>Market Data</h3>
        {% if trading_pair.market_data %}
          <p>OHLCV Data: {{ trading_pair.market_data }}</p>
        {% else %}
          <p>No market data available.</p>
        {% endif %}
      </div>

      <!-- News Tab -->
      <div class="tab-pane fade" id="news" role="tabpanel" aria-labelledby="news-tab">
        <h3>News Releases</h3>
        {% for news in cryptocurrency.news_set.all %}
          <div>
            <p>Title: {{ news.title }}</p>
            <p>Content: {{ news.content }}</p>
            <p>Source: <a href="{{ news.source }}" target="_blank">{{ news.source }}</a></p>
            <p>Timestamp: {{ news.timestamp }}</p>
          </div>
        {% endfor %}
      </div>

      <!-- Trades Tab -->
      <div class="tab-pane fade" id="trades" role="tabpanel" aria-labelledby="trades-tab">
        <h3>Last Trades</h3>
        {% for trade in cryptocurrency.trade_set.all %}
          <div>
            <p>Action: {{ trade.get_action_display }}</p>
            <p>Quantity: {{ trade.quantity }}</p>
            <p>Price: {{ trade.price }}</p>
            <p>Timestamp: {{ trade.timestamp }}</p>
          </div>
        {% endfor %}
      </div>
    </div>
  </section>


{% endblock %}

{% block extra_js %}
<script src="https://code.jquery.com/jquery-3.7.0.min.js"></script>
<script src="https://cdn.datatables.net/1.13.7/js/jquery.dataTables.min.js"></script>
<script src="https://cdn.datatables.net/1.13.7/js/dataTables.bootstrap5.min.js"></script>
<script>
  // Activate Bootstrap tabs
  $(document).ready(function() {
    $('#cryptoTabs a').on('click', function (e) {
      e.preventDefault();
      $(this).tab('show');
    });
  });
</script>
{% endblock %}

cryptokilla/market/templates/market/cryptocurrency_form.html
{% extends 'landing/base.html' %}
{%load static%}
{% load crispy_forms_tags %}

{% block extra_css %}

<style>
    :root {
        --main-font: 'Poppins', sans-serif;
        /*TO DO : to be selected from a list */
        --default-text-color: rgb(255, 255, 255);
        /* Can be selected by user */
        --background-image-url: url('{% static 'landing/images/header-background.jpg' %}');
        /* sizes: 1280x720 or 1920x1080 */
        --background-color-default: rgb(0, 0, 0, 0.3);
        --navbar-background-color: transparent;
        --navbar-scrolled-background-color: rgba(0, 0, 0, 0.3);
        --navbar-scrolled-background-blur: 10px;
        /*--btn-navbar-background-color: {{config.navbar_btn_color}};*/
    }

    body {
        font-family: var(--main-font);
        color: var(--default-text-color);
        background: var(--background-image-url) var(--background-color-default);
        background-blend-mode: multiply;
        background-position: center;
        background-size: cover;
        background-repeat: no-repeat;
    }

    .navbar {
        background-color: var(--navbar-background-color) !important;
        transition: all 0.5s ease-in-out;
    }

    .navbar-scrolled {
        background-color: var(--navbar-scrolled-background-color);
        backdrop-filter: blur(var(--navbar-scrolled-background-blur));
    }

    .navbar-btn {
        background-color: var(--btn-navbar-background-color);
    }
</style>
{% endblock %}

{% block content %}
<section id="create" class="vh-100 d-flex flex-row justify-content-center align-items-center">
<div class="container d-flex flex-column justify-content-center align-items-center">


  <h2>{% if cryptocurrency.id %}Edit{% else %}Create{% endif %} Cryptocurrency</h2>
  <form method="post" enctype="multipart/form-data" class="needs-validation" novalidate>
    {% csrf_token %}
    {{ form|crispy }}
    <button type="submit" class="btn btn-primary">Save</button>
    <a href="{% url 'cryptocurrency-list' %}" class="btn btn-secondary">Cancel</a>
  </form>
</div>
</section>
{% endblock %}

cryptokilla/market/templates/market/cryptocurrency_list.html
{% extends 'landing/base.html' %}
{%load static%}

{% block extra_css %}

<style>
    :root {
        --main-font: 'Poppins', sans-serif;
        /*TO DO : to be selected from a list */
        --default-text-color: rgb(255, 255, 255);
        /* Can be selected by user */
        --background-image-url: url('{% static 'landing/images/header-background.jpg' %}');
        /* sizes: 1280x720 or 1920x1080 */
        --background-color-default: rgb(0, 0, 0, 0.3);
        --navbar-background-color: transparent;
        --navbar-scrolled-background-color: rgba(0, 0, 0, 0.3);
        --navbar-scrolled-background-blur: 10px;
        /*--btn-navbar-background-color: {{config.navbar_btn_color}};*/
    }

    body {
        font-family: var(--main-font);
        color: var(--default-text-color);
        background: var(--background-image-url) var(--background-color-default);
        background-blend-mode: multiply;
        background-position: center;
        background-size: cover;
        /*background-repeat: no-repeat;*/
    }

    .navbar {
        background-color: var(--navbar-background-color) !important;
        transition: all 0.5s ease-in-out;
    }

    .navbar-scrolled {
        background-color: var(--navbar-scrolled-background-color);
        backdrop-filter: blur(var(--navbar-scrolled-background-blur));
    }

    .navbar-btn {
        background-color: var(--btn-navbar-background-color);
    }
</style>
{% endblock %}


{% block content %}
<section id="market" class="w-80 vh-100 d-flex flex-row justify-content-center align-items-start">
  <div class="container mt-5 " >
    <h2 style="margin-top: 50px;">Cryptocurrencies List</h2>
    <table id="cryptocurrenciesTable" class="table table-striped" >
      <thead>
        <tr>
          <th>Name</th>
          <th>Symbol</th>
          <th>Description</th>
          <th>Website</th>
          <th>Stablecoin</th>
          <th>Created At</th>
        </tr>
      </thead>
      <tbody>
        {% for cryptocurrency in cryptocurrencies %}
          <tr>
            <td>{{ cryptocurrency.name }}</td>
            <td>{{ cryptocurrency.symbol }}</td>
            <td>{{ cryptocurrency.description }}</td>
            <td><a href="{{ cryptocurrency.website }}" target="_blank">{{ cryptocurrency.website }}</a></td>
            <td>{% if cryptocurrency.is_stablecoin %}Yes{% else %}No{% endif %}</td>
            <td>{{ cryptocurrency.created_at }}</td>
          </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
  </section>


  
{% endblock %}

{% block extra_js %}
<script src="https://code.jquery.com/jquery-3.7.0.min.js"></script>
<script src="https://cdn.datatables.net/1.13.7/js/jquery.dataTables.min.js"></script>
<script src="https://cdn.datatables.net/1.13.7/js/dataTables.bootstrap5.min.js"></script>
<script>
  $(document).ready(function() {
    $('#cryptocurrenciesTable').DataTable();
  });
  </script>
{% endblock %}

cryptokilla/market/templates/market/cryptocurrency_news_confirm_delete.html
{% extends 'landing/base.html' %}

{% block content %}
  <h2>Confirm Deletion</h2>
  <p>Are you sure you want to delete "{{ cryptocurrency_news }}"?</p>
  <form method="post">
    {% csrf_token %}
    <button type="submit" class="btn btn-danger">Confirm</button>
  </form>
  <a href="{% url 'cryptocurrencynews-list' %}" class="btn btn-secondary">Cancel</a>
{% endblock %}

cryptokilla/market/templates/market/cryptocurrency_news_detail.html
{% extends 'landing/base.html' %}
{%load static%}
{% load crispy_forms_tags %}

{% block extra_css %}

<style>
    :root {
        --main-font: 'Poppins', sans-serif;
        /*TO DO : to be selected from a list */
        --default-text-color: rgb(255, 255, 255);
        /* Can be selected by user */
        --background-image-url: url('{% static 'landing/images/header-background.jpg' %}');
        /* sizes: 1280x720 or 1920x1080 */
        --background-color-default: rgb(0, 0, 0, 0.3);
        --navbar-background-color: transparent;
        --navbar-scrolled-background-color: rgba(0, 0, 0, 0.3);
        --navbar-scrolled-background-blur: 10px;
        /*--btn-navbar-background-color: {{config.navbar_btn_color}};*/
    }

    body {
        font-family: var(--main-font);
        color: var(--default-text-color);
        background: var(--background-image-url) var(--background-color-default);
        background-blend-mode: multiply;
        background-position: center;
        background-size: cover;
        background-repeat: no-repeat;
    }

    .navbar {
        background-color: var(--navbar-background-color) !important;
        transition: all 0.5s ease-in-out;
    }

    .navbar-scrolled {
        background-color: var(--navbar-scrolled-background-color);
        backdrop-filter: blur(var(--navbar-scrolled-background-blur));
    }

    .navbar-btn {
        background-color: var(--btn-navbar-background-color);
    }
</style>
{% endblock %}
{% block content %}
<section id="create" class="vh-100 d-flex flex-row justify-content-center align-items-center">
  <div class="container d-flex flex-column justify-content-center align-items-center">

    <!-- News Card -->
    <div class="card mt-5" style="width: 18rem;">
      <div class="card-body">
        <h5 class="card-title">{{ cryptocurrencynews.cryptocurrency.name }} News: {{ cryptocurrencynews.title }}</h5>
        <p class="card-text">{{ cryptocurrencynews.content }}</p>
        <a href="{% url 'cryptocurrencynews-list' %}" class="btn btn-secondary">Back to News</a>
      </div>
    </div>

  </div>
</section>
{% endblock %}

cryptokilla/market/templates/market/trading_pair_confirm_delete.html
{% extends 'landing/base.html' %}

{% block content %}
  <h2>Confirm Deletion</h2>
  <p>Are you sure you want to delete "{{ cryptocurrency }}"?</p>
  <form method="post">
    {% csrf_token %}
    <button type="submit" class="btn btn-danger">Confirm</button>
  </form>
  <a href="{% url 'cryptocurrency-list' %}" class="btn btn-secondary">Cancel</a>
{% endblock %}